apiVersion: v1
kind: Namespace
metadata:
  name: dreamspace

--- 

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dream-ingress
  namespace: dreamspace
spec:
  rules:
  - host: dream.social
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dream-service
            port:
              number: 9001
  ingressClassName: nginx
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dream-deploy
  namespace: dreamspace
spec:
  selector:
    matchLabels:
      app: dream-app
  replicas: 2 
  template:
    metadata:
      labels:
        app: dream-app 
    spec:
      containers:
      - name: dream-app
        image: dream:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9001

--- 

apiVersion: v1
kind: Service
metadata:
  name: dream-service
  namespace: dreamspace
  labels:
    app: dream-app
spec:
  type: ClusterIP
  ports:
    - port: 9001
      protocol: TCP
      targetPort: 9001
  selector:
    app: dream-app

